### ISSUE TITLE
Adapter Crash

### ISSUE THREAD

**Issue by m3gg3** [TA2k/ioBroker.mystrom#57]
<html>
<body>

2021-07-01 11:17:14.706 - error: mystrom.0 (28868) Cannot read property 'forEach' of undefined
--
2021-07-01 11:17:14.711 - error: mystrom.0 (28868) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-07-01 11:17:14.712 - error: mystrom.0 (28868) unhandled promise rejection: Cannot read property 'forEach' of undefined
2021-07-01 11:17:14.712 - error: mystrom.0 (28868) TypeError: Cannot read property 'forEach' of undefined
at /opt/iobroker/node_modules/iobroker.mystrom/main.js:139:51
at runMicrotasks ()
at runNextTicks (internal/process/task_queues.js:62:5)
at processImmediate (internal/timers.js:434:9)
2021-07-01 11:17:14.713 - error: mystrom.0 (28868) Cannot read property 'forEach' of undefined
2021-07-01 11:17:14.715 - info: mystrom.0 (28868) cleaned everything up...
2021-07-01 11:17:14.716 - info: mystrom.0 (28868) terminating
2021-07-01 11:17:14.717 - warn: mystrom.0 (28868) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-07-01 11:17:15.264 - error: host.iobroker-pi instance system.adapter.mystrom.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-07-01 11:17:15.265 - info: host.iobroker-pi Restart adapter system.adapter.mystrom.0 because enabled

</body>
</html>

**Comment by m3gg3** [comment]
reinstall
